strictness: veryhigh
doc-warnings: false
max-line-length: 88

pylint:
  disable:
    - too-few-public-methods
    - missing-module-docstring
    - missing-class-docstring
    - missing-function-docstring
