strictness: veryhigh
doc-warnings: false
max-line-length: 120

pylint:
  disable:
    - too-few-public-methods
    - missing-module-docstring
    - missing-class-docstring
    - missing-function-docstring

pep8:
  disable:
    - E501
